#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jan 10 16:19:47 EST 2024
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim Add4bitsTb_behav -key {Behavioral:sim_1:Functional:Add4bitsTb} -tclbatch Add4bitsTb.tcl -view /home/olivier/Downloads/pb_APP_log_comb_H2023/Add1Bit_tb_behav.wcfg -log simulate.log"
xsim Add4bitsTb_behav -key {Behavioral:sim_1:Functional:Add4bitsTb} -tclbatch Add4bitsTb.tcl -view /home/olivier/Downloads/pb_APP_log_comb_H2023/Add1Bit_tb_behav.wcfg -log simulate.log

